import Head from "next/head";
import "mapbox-gl/dist/mapbox-gl.css";
import React from "react";
import Map from "./components/Map";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;

export default function Home() {
  return (
    <>
      <Head>
        <title>Exandria Interactive</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen w-screen">
        <Map />
      </main>
    </>
  );
}
