import Head from "next/head";
import "mapbox-gl/dist/mapbox-gl.css";
import "react-map-gl-geocoder/dist/mapbox-gl-geocoder.css";
import React from "react";
import Map from "./components/Map";

export default function Home() {
    return (
        <>
            <Head>
                <title>Exandria Interactive</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="h-screen w-screen">
                <Map />
            </main>
        </>
    );
}
